services:
  neo4j:
    image: neo4j:2025.03.0
    ports:
      - "0.0.0.0:7474:7474"  # HTTP
      - "0.0.0.0:7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      # Enable APOC
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_server_config_strict__validation_enabled=false
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      
      # Memory settings from .env file
      - NEO4J_server_memory_heap_initial__size=${NEO4J_HEAP_MEMORY_INITIAL}
      - NEO4J_server_memory_heap_max__size=${NEO4J_HEAP_MEMORY_MAX}
      - NEO4J_server_memory_pagecache_size=${NEO4J_PAGE_CACHE}
      
      # Network settings
      - NEO4J_server_bolt_listen__address=0.0.0.0:7687
      - NEO4J_server_http_listen__address=0.0.0.0:7474
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./plugins:/plugins    # Important: This mounts the plugins directory
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"  # Use user/group IDs from .env file or default to 1000:1000
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
        compress: "true"
    deploy:
      resources:
        limits:
          memory: 8G    # Reduced memory requirements
          cpus: '2.0'   # Reduced CPU requirements
    ulimits:
      nofile:
        soft: 40000
        hard: 40000